-- ============================================================================
-- YM App — Geography Seed (regions -> subregions -> neighbor_nets)
-- ============================================================================
-- GENERATED FILE — do not edit by hand.
-- Regenerate: node docs/geography/generate-geo-seed.mjs
-- Source:     docs/geography/nn-master-cleaned.csv (see docs/geography/CLEANUP-LOG.md)
--
-- People (NNC / coordinators / core team) are NOT seeded here — they become
-- role_assignments in a post-Google-sync step that resolves emails to users.
-- ============================================================================

INSERT INTO regions (name, code, is_expansion) VALUES
  ('Northeast', 'NE', false),
  ('South', 'SO', false),
  ('Midwest', 'MW', false),
  ('Southeast', 'SE', false)
ON CONFLICT (code) DO NOTHING;

INSERT INTO subregions (region_id, name, code, is_expansion) VALUES
  ((SELECT id FROM regions WHERE code = 'NE'), 'New York East', 'NYE', false),
  ((SELECT id FROM regions WHERE code = 'NE'), 'New York West', 'NYW', true),
  ((SELECT id FROM regions WHERE code = 'NE'), 'New Jersey South', 'NJS', false),
  ((SELECT id FROM regions WHERE code = 'NE'), 'New Jersey Central', 'NJC', false),
  ((SELECT id FROM regions WHERE code = 'NE'), 'New Jersey North', 'NJN', false),
  ((SELECT id FROM regions WHERE code = 'SO'), 'Houston', 'HOU', false),
  ((SELECT id FROM regions WHERE code = 'SO'), 'Dallas East', 'DLE', false),
  ((SELECT id FROM regions WHERE code = 'SO'), 'Dallas West', 'DLW', false),
  ((SELECT id FROM regions WHERE code = 'MW'), 'Chicago', 'CHI', false),
  ((SELECT id FROM regions WHERE code = 'SE'), 'Georgia', 'GA', false),
  ((SELECT id FROM regions WHERE code = 'NE'), 'Massachusetts', 'MA', false),
  ((SELECT id FROM regions WHERE code = 'MW'), 'Kentucky', 'KY', false),
  ((SELECT id FROM regions WHERE code = 'NE'), 'Connecticut', 'CT', false),
  ((SELECT id FROM regions WHERE code = 'SE'), 'Florida', 'FL', false),
  (NULL, 'Northern Virginia', 'NVA', true),
  (NULL, 'Central/South Virginia', 'CSVA', true),
  (NULL, 'Maryland', 'MD', true),
  ((SELECT id FROM regions WHERE code = 'NE'), 'Pennsylvania', 'PA', false),
  (NULL, 'Washington', 'WA', true),
  (NULL, 'West', 'WEST', true),
  (NULL, 'West Virginia', 'WV', true),
  (NULL, 'Minnesota', 'MN', true)
ON CONFLICT (code) DO NOTHING;

INSERT INTO neighbor_nets (subregion_id, name, location, address, meeting_day, fundraising_link, is_expansion) VALUES
  ((SELECT id FROM subregions WHERE code = 'NYE'), 'Jamaica', 'ICNA Markaz', NULL, 'Friday', 'https://giving.ymsite.com/-/NFNDMRUW?member=SNKQPTXV', false),
  ((SELECT id FROM subregions WHERE code = 'NYE'), 'Queens Village', NULL, NULL, NULL, 'https://giving.ymsite.com/-/NTUJDUHF?member=SNKQPTXV', false),
  ((SELECT id FROM subregions WHERE code = 'NYE'), 'Valley Stream', NULL, NULL, NULL, 'https://giving.ymsite.com/-/NVAZYHJD?member=SNKQPTXV', false),
  ((SELECT id FROM subregions WHERE code = 'NYE'), 'Shelter Rock', 'North Shore Islamic Center (NSIC)', NULL, 'Saturday', 'https://giving.ymsite.com/-/NATPKUWG?member=SNKQPTXV', false),
  ((SELECT id FROM subregions WHERE code = 'NYE'), 'East Meadow', 'Long Island Muslim Center (LIMS)', NULL, 'Friday', 'https://giving.ymsite.com/-/NHGAWSDG?member=SNKQPTXV', false),
  ((SELECT id FROM subregions WHERE code = 'NYE'), 'Melville', 'Islamic center of Melville (ICM)', NULL, 'Sunday', 'https://giving.ymsite.com/-/NEWGSVER?member=SNKQPTXV', false),
  ((SELECT id FROM subregions WHERE code = 'NYE'), 'Deer Park', 'Islamic center of Deer Park (ICDP)', NULL, 'Saturday', 'https://giving.ymsite.com/-/NNTRWVHC?member=SNKQPTXV', false),
  ((SELECT id FROM subregions WHERE code = 'NYE'), 'Ronkonkoma', 'Suffolk Islamic Center (SIC)', NULL, 'Saturday', 'https://giving.ymsite.com/-/NWNGSKES?member=SNKQPTXV', false),
  ((SELECT id FROM subregions WHERE code = 'NYE'), 'NYIT', 'New York institute of technology (NYIT)', NULL, 'Tuesday', 'https://giving.ymsite.com/-/NMUEVASB?member=SNKQPTXV', false),
  ((SELECT id FROM subregions WHERE code = 'NYW'), 'Brooklyn', 'Quba Mosque', '1323 Foster Ave, Brooklyn, NY 11230', 'Saturday', 'https://giving.ymsite.com/-/NBTDBVDB?member=SNKQPTXV', false),
  ((SELECT id FROM subregions WHERE code = 'NYW'), 'Westchester', 'Westchester Muslim Center', '22 Brookfield Rd, Mt Vernon, NY 10552', 'Saturday', NULL, false),
  ((SELECT id FROM subregions WHERE code = 'NYW'), 'White Plains', 'White Plains Islamic Center', '49 Russell Street, White Plains NY 10606', 'Saturday', 'https://giving.ymsite.com/-/NCJBMYZQ?member=SNKQPTXV', false),
  ((SELECT id FROM subregions WHERE code = 'NYW'), 'Stamford', 'ICCNY', '1558 Washington Blvd, Stamford, CT 06902', 'Sunday', 'https://giving.ymsite.com/-/NCFVLSXV?member=SNKQPTXV', false),
  ((SELECT id FROM subregions WHERE code = 'NYW'), 'Rockland', 'Rockland Islamic Center', '481 Mountain View Ave, Valley Cottage, NY 10989', 'Friday', 'https://giving.ymsite.com/-/NRRYQTJK?member=SNKQPTXV', false),
  ((SELECT id FROM subregions WHERE code = 'NJS'), '571', 'MCGP', NULL, NULL, 'https://giving.ymsite.com/-/NAKNBNGT?member=SNKQPTXV', false),
  ((SELECT id FROM subregions WHERE code = 'NJS'), 'Montyboro', 'Muslim Center of Somerset County (MCSC)', NULL, NULL, 'https://giving.ymsite.com/-/NJASKHSJ?member=SNKQPTXV', false),
  ((SELECT id FROM subregions WHERE code = 'NJS'), 'South Jersey', 'GCLEA', NULL, NULL, 'https://giving.ymsite.com/-/NTQFKFKK?member=SNKQPTXV', false),
  ((SELECT id FROM subregions WHERE code = 'NJS'), 'South Brunswick', NULL, NULL, NULL, 'https://giving.ymsite.com/-/NUNYEWVR?member=SNKQPTXV', false),
  ((SELECT id FROM subregions WHERE code = 'NJS'), 'Blackwood', NULL, NULL, NULL, 'https://giving.ymsite.com/-/NHLDPHLH?member=SNKQPTXV', false),
  ((SELECT id FROM subregions WHERE code = 'NJC'), 'Piscataway', 'Muslim Center of Middlesex County (MCMC)', NULL, NULL, 'https://giving.ymsite.com/-/NLQCEJCV?member=SNKQPTXV', false),
  ((SELECT id FROM subregions WHERE code = 'NJC'), 'Woodbridge', 'MCNJ', NULL, NULL, 'https://giving.ymsite.com/-/NLHHVPJS?member=SNKQPTXV', false),
  ((SELECT id FROM subregions WHERE code = 'NJC'), 'Old Bridge', 'Masjid Sadar/Darul Arqam', NULL, NULL, 'https://giving.ymsite.com/-/NEZRUCDP?member=SNKQPTXV', false),
  ((SELECT id FROM subregions WHERE code = 'NJC'), 'Edison', 'Masjid Al Wali', NULL, NULL, 'https://giving.ymsite.com/-/NRZKYJDN?member=SNKQPTXV', false),
  ((SELECT id FROM subregions WHERE code = 'NJN'), 'Bayonne', 'Bayonne Mosque and Community Center', '109 E 24th St, Bayonne, NJ 07002', 'Friday', 'https://giving.ymsite.com/-/NFAXNDFF?member=SLDEWSVK', false),
  ((SELECT id FROM subregions WHERE code = 'NJN'), 'Newark', 'NIA Masjid and Community Center', '231 Roseville Ave, Newark, NJ 07107', 'Friday', 'https://giving.ymsite.com/-/NUZMBAST?member=SLDEWSVK', false),
  ((SELECT id FROM subregions WHERE code = 'NJN'), 'North Hudson', 'North Hudson Islamic Educational Center', '4613 Cottage Pl, Union City, NJ 07087', 'Friday', NULL, false),
  ((SELECT id FROM subregions WHERE code = 'NJN'), 'Wayne', 'Dar Al Hadith', '970 Black Oak Ridge Rd, Wayne, NJ 07470', 'Saturday', 'https://giving.ymsite.com/-/NLRAGVXV?member=SNKQPTXV', false),
  ((SELECT id FROM subregions WHERE code = 'NJN'), 'Jersey City', 'Masjid Tawheed/Masjid Salaam', '984 West Side Ave, Jersey City, NJ 07306', 'Friday', 'https://giving.ymsite.com/-/NKVPUZPR?member=SLDEWSVK', false),
  ((SELECT id FROM subregions WHERE code = 'NJN'), 'Paramus', 'Muslim Community Center of Paramus (Fusion)', '650 Pascack Rd, Paramus, NJ 07652', 'Friday', 'https://giving.ymsite.com/-/NURVPDHW?member=SLDEWSVK', false),
  ((SELECT id FROM subregions WHERE code = 'NJN'), 'Morris County', 'ICCC', '879 S Beverwyck Rd, Parsippany, NJ 07054', 'Friday', 'https://giving.ymsite.com/-/NHKQTNBL?member=SNKQPTXV', false),
  ((SELECT id FROM subregions WHERE code = 'NJN'), 'Teaneck', 'Darul Islah', '320 Fabry Terrace, Teaneck, NJ 07666', 'Friday', 'https://giving.ymsite.com/-/NKKAYBMK?member=SLDEWSVK', false),
  ((SELECT id FROM subregions WHERE code = 'HOU'), 'Masjid Maryam', 'Maryam Masjid', 'Maryam Islamic Center', 'Saturday', 'https://giving.ymsite.com/-/NXHRMAVF?member=SNKQPTXV', false),
  ((SELECT id FROM subregions WHERE code = 'HOU'), 'Clear Lake', 'Quba Masjid', 'Quba Academy', 'Friday', 'https://giving.ymsite.com/-/NXYKQSKH?member=SNKQPTXV', false),
  ((SELECT id FROM subregions WHERE code = 'HOU'), 'Bear Creek', 'Masjid Al-Mustafa', 'ISGH Bear Creek Islamic Center (BCIC) | Masjid Al-Mustafa', 'Saturday', 'https://giving.ymsite.com/-/NPDUHRQX?member=SNKQPTXV', false),
  ((SELECT id FROM subregions WHERE code = 'HOU'), 'Cinco Ranch', 'Masjid Aqsa', 'Masjid Aqsa', 'Saturday', 'https://giving.ymsite.com/-/NKGYFWNR?member=SNKQPTXV', false),
  ((SELECT id FROM subregions WHERE code = 'HOU'), 'College Station', 'ICBCS', 'Islamic Community of Bryan- College Station (ICBCS)', 'Thursday', 'https://giving.ymsite.com/-/NKPYZZBE?member=SNKQPTXV', false),
  ((SELECT id FROM subregions WHERE code = 'HOU'), 'Synott', 'Masjid Attaqwa', 'ISGH Masjid At-Taqwa', 'Friday', 'https://giving.ymsite.com/-/NZAHDMPN?member=SNKQPTXV', false),
  ((SELECT id FROM subregions WHERE code = 'HOU'), 'River Oaks', 'River Oaks Islamic Center', 'ISGH River Oaks Islamic Center (ROIC)', 'Friday', 'https://giving.ymsite.com/-/NBPLZXCR?member=SNKQPTXV', false),
  ((SELECT id FROM subregions WHERE code = 'HOU'), 'Pearland', 'Pearland Islamic Center', 'Pearland Islamic Center (PIC) - ISGH', 'Saturday', 'https://giving.ymsite.com/-/NQZVJSJS?member=SNKQPTXV', false),
  ((SELECT id FROM subregions WHERE code = 'HOU'), 'Spring', 'Masjid Ibrahim / Masjid Bilal', 'Masjid Ibrahim- Klein Islamic Center', 'Saturday', 'https://giving.ymsite.com/-/NRRDBFRL?member=SNKQPTXV', false),
  ((SELECT id FROM subregions WHERE code = 'HOU'), 'Cypress', 'ICNA Outreach Center', 'ICNA Outreach Center', 'Friday', 'https://giving.ymsite.com/-/NMLWGMDX?member=SNKQPTXV', false),
  ((SELECT id FROM subregions WHERE code = 'DLE'), 'Prosper', 'Islamic Center of Prosper and Celina', '861 N Coleman St #190, Prosper, TX 75078', 'Friday', 'https://giving.ymsite.com/-/NWAALBHL?member=SNKQPTXV', false),
  ((SELECT id FROM subregions WHERE code = 'DLE'), 'East Plano', 'East Plano Islamic Center', '4700 14th St, Plano, TX 75074', 'Friday', 'https://giving.ymsite.com/-/NWYTYUFR?member=SNKQPTXV', false),
  ((SELECT id FROM subregions WHERE code = 'DLE'), 'Richardson', 'Islamic Association of North Texas', '840 Abrams Rd, Richardson, TX 75081', 'Saturday', 'https://giving.ymsite.com/-/NLJBTYXN?member=SNKQPTXV', false),
  ((SELECT id FROM subregions WHERE code = 'DLE'), 'Frisco', 'Islamic Center of Frisco', '11137 Frisco St, Frisco, TX 75033', 'Saturday', 'https://giving.ymsite.com/-/NFVUUXEN?member=SNKQPTXV', false),
  ((SELECT id FROM subregions WHERE code = 'DLW'), 'Carrollton', 'Masjid Ar-Rahman', '1901 Kelly Blvd, Carrollton, TX 75006', 'Friday', 'https://giving.ymsite.com/-/NBYLKWMY?member=SNKQPTXV', false),
  ((SELECT id FROM subregions WHERE code = 'DLW'), 'Valley Ranch', 'Valley Ranch Islamic Center', '351 Ranchview Dr, Irving, TX 75063', 'Friday', 'https://giving.ymsite.com/-/NRNTNJQQ?member=SNKQPTXV', false),
  ((SELECT id FROM subregions WHERE code = 'DLW'), 'Euless', 'Islamic Center of Euless', '203 S Ector Dr, Euless, TX 76040', 'Friday', 'https://giving.ymsite.com/-/NZUGVJJS?member=SNKQPTXV', false),
  ((SELECT id FROM subregions WHERE code = 'DLW'), 'Irving', 'Islamic Center of Irving', '2555 Esters Rd, Irving, TX 75062', 'Friday', 'https://giving.ymsite.com/-/NQDBBZNL?member=SNKQPTXV', false),
  ((SELECT id FROM subregions WHERE code = 'DLE'), '75', 'Masjid Salahuddin', '4030 Split Trail Rd, Plano, TX 75074', 'Saturday', 'https://giving.ymsite.com/-/NACXHRQZ?member=SNKQPTXV', false),
  ((SELECT id FROM subregions WHERE code = 'DLW'), 'Colleyville', NULL, NULL, NULL, 'https://giving.ymsite.com/-/NZGXULZB?member=SNKQPTXV', false),
  ((SELECT id FROM subregions WHERE code = 'DLW'), 'Southlake', NULL, NULL, NULL, 'https://giving.ymsite.com/-/NFDKGCBZ?member=SNKQPTXV', false),
  ((SELECT id FROM subregions WHERE code = 'CHI'), 'IFN', 'Islamic Foundation North', '1751 O''Plaine Rd, Libertyville, IL 60048', 'Friday', 'https://giving.ymsite.com/-/NWUPGLQR?member=SNKQPTXV', false),
  ((SELECT id FROM subregions WHERE code = 'CHI'), 'Niles', 'Muslims Education Center', '8601 Menard Ave, Morton Grove, IL 60053', 'Saturday', 'https://giving.ymsite.com/-/NLQFDMKR?member=SNKQPTXV', false),
  ((SELECT id FROM subregions WHERE code = 'CHI'), 'Westside', 'ICNA Center', '1S270 Summit Ave, Oakbrook Terrace, IL 60181', 'Saturday', 'https://giving.ymsite.com/-/NRXRUVZQ?member=SNKQPTXV', false),
  ((SELECT id FROM subregions WHERE code = 'CHI'), 'Plainfield', 'Al Aqsa Community Center', '17940 Bronk Rd, Plainfield, IL 60586', 'Friday', 'https://giving.ymsite.com/-/NGXBFLPW?member=SNKQPTXV', false),
  ((SELECT id FROM subregions WHERE code = 'CHI'), 'Potter', 'Islamic Center of Des Plaines', '480 Potter Rd, Des Plaines, IL 60016', 'Saturday', 'https://giving.ymsite.com/-/NUFDXMZD?member=SNKQPTXV', false),
  ((SELECT id FROM subregions WHERE code = 'CHI'), 'Bolingbrook', 'Furqan Foundation', '642 Forestwood Dr, Romeoville, IL 60446', 'Saturday', 'https://giving.ymsite.com/-/NHPRHEKU?member=SNKQPTXV', false),
  ((SELECT id FROM subregions WHERE code = 'CHI'), 'Wheaton', 'Islamic Center of Wheaton', '900 E Geneva Rd, Wheaton, IL 60187', 'Saturday', 'https://giving.ymsite.com/-/NYACZJQN?member=SNKQPTXV', false),
  ((SELECT id FROM subregions WHERE code = 'CHI'), 'ICWS', 'Islamic Center of Western Suburbs', '28W774 Army Trail Rd, West Chicago, IL 60185', 'Friday', 'https://giving.ymsite.com/-/NWJECKHJ?member=SNKQPTXV', false),
  ((SELECT id FROM subregions WHERE code = 'GA'), 'Alpharetta', 'Hamzah Islamic Center', NULL, NULL, 'https://giving.ymsite.com/-/NKXHYSFA?member=SNKQPTXV', false),
  ((SELECT id FROM subregions WHERE code = 'GA'), 'Liburn', 'Masjid Omar Bin Abdul Aziz Mosque', NULL, NULL, 'https://giving.ymsite.com/-/NHNRXCNM?member=SNKQPTXV', false),
  ((SELECT id FROM subregions WHERE code = 'GA'), 'Suwanee', 'Gwinnett Islamic Circle', NULL, NULL, 'https://giving.ymsite.com/-/NNAFZAKS?member=SNKQPTXV', false),
  ((SELECT id FROM subregions WHERE code = 'GA'), 'Roswell', 'Roswell Community Masjid', NULL, NULL, 'https://giving.ymsite.com/-/NZLMAUKG?member=SNKQPTXV', false),
  ((SELECT id FROM subregions WHERE code = 'GA'), 'East Cobb', 'Ibadurrahman', NULL, NULL, 'https://giving.ymsite.com/-/NUZTPDQC?member=SNKQPTXV', false),
  ((SELECT id FROM subregions WHERE code = 'GA'), 'Cumming', 'Masjid Rahman', NULL, NULL, 'https://giving.ymsite.com/-/NSTWVMTJ?member=SNKQPTXV', false),
  ((SELECT id FROM subregions WHERE code = 'MA'), 'Lowell', 'Islamic Society of Greater Lowell', '5 Courthouse Ln, Chelmsford, MA 01824', 'Saturday', 'https://giving.ymsite.com/-/NFUUXCRV?member=SNKQPTXV', false),
  ((SELECT id FROM subregions WHERE code = 'MA'), 'Metrowest', 'Boroughs Islamic Center (BIS)', '6 Bellows Rd, Westborough, MA 01581', 'Sunday', 'https://giving.ymsite.com/-/NRZWDVKC?member=SNKQPTXV', false),
  ((SELECT id FROM subregions WHERE code = 'MA'), 'Pawtucket', 'The Muslim Society of Rhode Island - Masjid Al-Rahman', '665 Central Ave, Pawtucket, RI 02861', 'Saturday', 'https://giving.ymsite.com/-/NWAAUKAR?member=SNKQPTXV', false),
  ((SELECT id FROM subregions WHERE code = 'MA'), 'Sharon', 'Islamic Center of New Egland', '74 Chase Dr, Sharon, MA 02067', 'Saturday', 'https://giving.ymsite.com/-/NAXWPUEK?member=SNKQPTXV', false),
  ((SELECT id FROM subregions WHERE code = 'MA'), 'Quincy', 'Islamic Center of New Egland', '470 South St, Quincy, MA 02169', 'Friday', 'https://giving.ymsite.com/-/NTSJHWRG?member=SNKQPTXV', false),
  ((SELECT id FROM subregions WHERE code = 'MA'), 'Worcester', 'Worscester Islamic Center (WIC)', '248 Mountain St E, Worcester, MA 01606', 'Saturday', 'https://giving.ymsite.com/-/NDKJQJFK?member=SNKQPTXV', false),
  ((SELECT id FROM subregions WHERE code = 'KY'), 'Bowling Green', NULL, NULL, NULL, 'https://giving.ymsite.com/-/NXLBQWAN?member=SNKQPTXV', false),
  ((SELECT id FROM subregions WHERE code = 'KY'), 'Lexington', NULL, NULL, NULL, 'https://giving.ymsite.com/-/NDHZBFDJ?member=SNKQPTXV', false),
  ((SELECT id FROM subregions WHERE code = 'KY'), '4th St', NULL, NULL, NULL, 'https://giving.ymsite.com/-/NVVPZYBN?member=SNKQPTXV', false),
  ((SELECT id FROM subregions WHERE code = 'CT'), 'Berlin', 'Islamic Association of Greater Hartford', '1781 Berlin Tpke, Berlin, CT 06037', 'Friday', 'https://giving.ymsite.com/-/NGYEFUXR?member=SNKQPTXV', false),
  ((SELECT id FROM subregions WHERE code = 'CT'), 'Windsor Locks', 'Islamic Center of Windsor Locks', '332 Elm St, Windsor Locks, CT 06096', 'Saturday', 'https://giving.ymsite.com/-/NBMJASHJ?member=SNKQPTXV', false),
  ((SELECT id FROM subregions WHERE code = 'CT'), 'New Britain', 'Islamic Association of Central Connecticut', '100 Arch St, New Britain, CT 06051', 'Friday', 'https://giving.ymsite.com/-/NSCFNQJN?member=SNKQPTXV', false),
  ((SELECT id FROM subregions WHERE code = 'CT'), 'Middletown', 'Omar Islamic Center', '24 Broad St, Middletown, CT 06457', 'Sunday', 'https://giving.ymsite.com/-/NGHBPFEA?member=SNKQPTXV', false),
  ((SELECT id FROM subregions WHERE code = 'CT'), 'New Haven', 'New Haven Islamic Center - NHIC - Orange Masjid', '254 Bull Hill Ln, Orange, CT 06477', 'Saturday', 'https://giving.ymsite.com/-/NFLZAXZW?member=SNKQPTXV', false),
  ((SELECT id FROM subregions WHERE code = 'FL'), 'Pompano', NULL, NULL, NULL, 'https://giving.ymsite.com/-/NSFPUBTZ?member=SNKQPTXV', false),
  ((SELECT id FROM subregions WHERE code = 'FL'), 'Pines', NULL, NULL, NULL, 'https://giving.ymsite.com/-/NPJDXWVT?member=SNKQPTXV', false),
  ((SELECT id FROM subregions WHERE code = 'FL'), 'SoFlo', 'Islamic Foundation of South Florida', NULL, NULL, 'https://giving.ymsite.com/-/NZYCUEKX?member=SNKQPTXV', false),
  ((SELECT id FROM subregions WHERE code = 'FL'), 'Gainesville - FL', NULL, NULL, NULL, 'https://giving.ymsite.com/-/NQSQHNGF?member=SNKQPTXV', false),
  ((SELECT id FROM subregions WHERE code = 'FL'), 'St Johns', NULL, NULL, NULL, 'https://giving.ymsite.com/-/NWCQNQUT?member=SNKQPTXV', false),
  ((SELECT id FROM subregions WHERE code = 'FL'), 'Jacksonville', 'Islamic Center of Northeast Florida', NULL, NULL, 'https://giving.ymsite.com/-/NJEUFLJK?member=SNKQPTXV', false),
  ((SELECT id FROM subregions WHERE code = 'NVA'), 'Gainesville - VA', NULL, NULL, NULL, 'https://giving.ymsite.com/-/NVEWCHMT?member=SNKQPTXV', false),
  ((SELECT id FROM subregions WHERE code = 'NVA'), 'Woodbridge - VA', NULL, NULL, NULL, 'https://giving.ymsite.com/-/NAQNBZCL?member=SNKQPTXV', false),
  ((SELECT id FROM subregions WHERE code = 'NVA'), 'Falls Church', NULL, NULL, NULL, 'https://giving.ymsite.com/-/NWRATJGW?member=SNKQPTXV', false),
  ((SELECT id FROM subregions WHERE code = 'NVA'), 'Sterling', NULL, NULL, NULL, 'https://giving.ymsite.com/-/NZJVJTAY?member=SNKQPTXV', false),
  ((SELECT id FROM subregions WHERE code = 'NVA'), 'Burke', NULL, NULL, NULL, 'https://giving.ymsite.com/-/NEUQPYAH?member=SNKQPTXV', false),
  ((SELECT id FROM subregions WHERE code = 'CSVA'), 'Chesterfield', NULL, NULL, NULL, 'https://giving.ymsite.com/-/NEYQVFPY?member=SNKQPTXV', false),
  ((SELECT id FROM subregions WHERE code = 'CSVA'), 'Glen Allen', NULL, NULL, NULL, 'https://giving.ymsite.com/-/NUKADHNF?member=SNKQPTXV', false),
  ((SELECT id FROM subregions WHERE code = 'CSVA'), 'Virginia Tech', NULL, NULL, NULL, 'https://giving.ymsite.com/-/NUKADHNF?member=SNKQPTXV', false),
  ((SELECT id FROM subregions WHERE code = 'MD'), 'Salisbury', NULL, NULL, NULL, 'https://giving.ymsite.com/-/NPLCSKNS?member=SNKQPTXV', false),
  ((SELECT id FROM subregions WHERE code = 'MD'), 'Gaithersburg', NULL, NULL, NULL, 'https://giving.ymsite.com/-/NWFLQAJW?member=SNKQPTXV', false),
  ((SELECT id FROM subregions WHERE code = 'MD'), 'Baltimore', NULL, NULL, NULL, 'https://giving.ymsite.com/-/NKXNBEPH?member=SNKQPTXV', false),
  ((SELECT id FROM subregions WHERE code = 'MD'), 'Whitemarsh', NULL, NULL, NULL, 'https://giving.ymsite.com/-/NWGRKFBE?member=SNKQPTXV', false),
  ((SELECT id FROM subregions WHERE code = 'MD'), 'Annapolis', NULL, NULL, NULL, 'https://giving.ymsite.com/-/NNZQHNAB?member=SNKQPTXV', false),
  ((SELECT id FROM subregions WHERE code = 'MD'), 'Lanham', NULL, NULL, NULL, 'https://giving.ymsite.com/-/NJTLCXGH?member=SNKQPTXV', false),
  ((SELECT id FROM subregions WHERE code = 'MD'), 'Silver Spring', NULL, NULL, NULL, 'https://giving.ymsite.com/-/NLVFSBVV?member=SNKQPTXV', false),
  ((SELECT id FROM subregions WHERE code = 'PA'), 'Harrisburg', 'Islamic Center of Pennsylvania', '5138 East Trindle Road, Mechanicsburg, PA 17050', 'Saturday', 'https://giving.ymsite.com/-/NZYDDXQM?member=SNKQPTXV', false),
  ((SELECT id FROM subregions WHERE code = 'PA'), 'Norristown', 'Norristown Islamic Society', '5 W Elm St, Norristown, PA 19401', 'Saturday', 'https://giving.ymsite.com/-/NTGJHBEB?member=SNKQPTXV', false),
  ((SELECT id FROM subregions WHERE code = 'PA'), 'North Penn', 'North Penn Mosque', 'North Penn Mosque, 600 Maple Ave, Lansdale, PA 19446', 'Saturday', 'https://giving.ymsite.com/-/NSFRGMWN?member=SNKQPTXV', false),
  ((SELECT id FROM subregions WHERE code = 'PA'), 'Khair', 'Khair Community Center', '1079 Egypt Rd, Phoenixville, PA 19460', 'Friday', 'https://giving.ymsite.com/-/NBWLHZAR?member=SNKQPTXV', false),
  ((SELECT id FROM subregions WHERE code = 'PA'), 'Penn', 'University of Pennsylvania', '3451 Walnut St, Philadelphia, PA 19104', 'Friday', 'https://giving.ymsite.com/-/NYEUGQQM?member=SNKQPTXV', false),
  ((SELECT id FROM subregions WHERE code = 'PA'), 'Devon', 'Islamic Society of Greater Valley Forge', '958 N Valley Forge Rd, Devon, PA 19333', 'Saturday', NULL, false),
  ((SELECT id FROM subregions WHERE code = 'PA'), 'West Chester', 'Islamic Society of Chester County', '1001 Pottstown Pike, West Chester, PA 19380', 'Saturday', NULL, false),
  ((SELECT id FROM subregions WHERE code = 'PA'), 'Upper Darby', 'Islamic Center of Delaware County', '2502 Township Line Rd, Havertown, PA 19083', 'Saturday', 'https://giving.ymsite.com/-/NAANKYAS?member=SNKQPTXV', false),
  ((SELECT id FROM subregions WHERE code = 'WA'), 'Bellevue', NULL, NULL, NULL, 'https://giving.ymsite.com/-/NYMYBTGP?member=SNKQPTXV', false),
  ((SELECT id FROM subregions WHERE code = 'WA'), 'Bothell', NULL, NULL, NULL, 'https://giving.ymsite.com/-/NWXNFQEP?member=SNKQPTXV', false),
  ((SELECT id FROM subregions WHERE code = 'WEST'), 'LV', NULL, NULL, NULL, 'https://giving.ymsite.com/-/NRQPGKWT?member=SNKQPTXV', false),
  ((SELECT id FROM subregions WHERE code = 'WEST'), 'AZ', NULL, NULL, NULL, 'https://giving.ymsite.com/-/NPCRYSLD?member=SNKQPTXV', false),
  ((SELECT id FROM subregions WHERE code = 'WEST'), 'LA', NULL, NULL, NULL, 'https://giving.ymsite.com/-/NLSKGKNL?member=SNKQPTXV', false),
  ((SELECT id FROM subregions WHERE code = 'WV'), 'Morgantown', NULL, NULL, NULL, 'https://giving.ymsite.com/-/NDWSQDLD?member=SNKQPTXV', false),
  ((SELECT id FROM subregions WHERE code = 'WV'), 'Huntington', NULL, NULL, NULL, 'https://giving.ymsite.com/-/NDBVBLZU?member=SNKQPTXV', false),
  ((SELECT id FROM subregions WHERE code = 'WV'), 'Charleston', NULL, NULL, NULL, 'https://giving.ymsite.com/-/NZXGDNLT?member=SNKQPTXV', false),
  ((SELECT id FROM subregions WHERE code = 'MN'), 'Blaine', NULL, NULL, NULL, 'https://giving.ymsite.com/-/NTAYYPPM?member=SNKQPTXV', false)
ON CONFLICT (subregion_id, name) DO NOTHING;
