-- YMLC 2026 — conference data seed (NOT canonical schema seed)
-- Run by hand against the remote via the Supabase SQL editor or psql.
-- Generated from "YMLC 2026 Schedule.xlsx" + "YMLC 2026 Attendees.csv".
--
-- Idempotent & RE-RUN SAFE ONLY WHILE IN DRAFT: the DELETE below cascades to
-- sessions + conference_attendees + any signups/check-ins/feedback. Once the
-- conference is published and attendees have signed up, DO NOT re-run — it will
-- wipe their signups. Edit in place and apply the specific rows instead.
--
-- Sessions: 42 total (11 breaks, 31 content).
-- Capacity: uncapped (NULL) everywhere — decided for a 213-person event.
-- Attendees: 204 emails resolved against public.users at apply time
--   (email-keyed resolver survives DB wipes; missing users are silently skipped).
-- Check-in codes: 6/31 filled in; the rest are NULL (TODO).

BEGIN;

DELETE FROM conferences WHERE name = 'YMLC 2026';  -- pre-publish re-run guard

WITH conf AS (
  INSERT INTO conferences (name, start_date, end_date, timezone, scope_level, status)
  VALUES ('YMLC 2026', DATE '2026-07-10', DATE '2026-07-12',
          'America/New_York', 'national', 'draft')
  RETURNING id
)
INSERT INTO sessions
  (conference_id, start_at, end_at, title, description, room, is_break, capacity, check_in_code)
SELECT conf.id, v.start_at, v.end_at, v.title, v.description, v.room, v.is_break, v.capacity, v.code
FROM conf, (VALUES
    (TIMESTAMPTZ '2026-07-10 11:00:00 America/New_York', TIMESTAMPTZ '2026-07-10 14:00:00 America/New_York', 'Arrival and Registration', NULL, 'Grand Ballroom ABC', true, NULL::integer, NULL),
    (TIMESTAMPTZ '2026-07-10 14:00:00 America/New_York', TIMESTAMPTZ '2026-07-10 15:30:00 America/New_York', 'Jumuah, Asr, and Lunch', NULL, 'Grand Ballroom ABC', true, NULL::integer, NULL),
    (TIMESTAMPTZ '2026-07-10 18:00:00 America/New_York', TIMESTAMPTZ '2026-07-10 19:15:00 America/New_York', 'Main Session · State of YM / Intro to YMLC / Expectations', NULL, 'Grand Ballroom ABC', false, NULL::integer, 'nnc2026'),
    (TIMESTAMPTZ '2026-07-10 19:15:00 America/New_York', TIMESTAMPTZ '2026-07-10 19:45:00 America/New_York', 'Main Session · Crash Course: YM''s Role in Social Justice / Civic Engagement', 'The Prophet SAW and the sahaba were individuals who constantly thought about ills in society that and what solutions they could bring about. This is a workshop to start the reflection process of what negative/positive aspects of society we see in our local communities, country, and worldwide. Then we will start to think of possible solutions or possible pathways to those solutions. The objective of this session is not to inact change, rather demonstrate how we should approach our lives and the challenges that we are unaware of around our world. (ex: future problems in sports gambling and betting, masjid politics and disregard for age based problems, continued deteriation of education in the US, etc)', 'Grand Ballroom ABC', false, NULL::integer, 'lebronreadit'),
    (TIMESTAMPTZ '2026-07-10 19:45:00 America/New_York', TIMESTAMPTZ '2026-07-10 20:30:00 America/New_York', 'Maghrib and Isha', NULL, 'Grand Ballroom ABC', true, NULL::integer, NULL),
    (TIMESTAMPTZ '2026-07-10 21:00:00 America/New_York', TIMESTAMPTZ '2026-07-11 00:00:00 America/New_York', 'Dinner and Activities', NULL, 'Grand Ballroom ABC', true, NULL::integer, NULL),
    (TIMESTAMPTZ '2026-07-11 09:00:00 America/New_York', TIMESTAMPTZ '2026-07-11 10:00:00 America/New_York', 'Breakfast', NULL, 'Lobby', true, NULL::integer, NULL),
    (TIMESTAMPTZ '2026-07-11 10:30:00 America/New_York', TIMESTAMPTZ '2026-07-11 11:00:00 America/New_York', 'Main Session · Quran Recitation', NULL, 'Grand Ballroom ABC', false, NULL::integer, 'holy'),
    (TIMESTAMPTZ '2026-07-11 11:00:00 America/New_York', TIMESTAMPTZ '2026-07-11 12:00:00 America/New_York', 'Main Session · Prophetic Tradition of Leadership', 'Throughout history, Muslims have faced moments of deep crisis and decline, yet time and again, individuals rose to meet the challenges of their era and worked to revive the strength and spirit of the Ummah. In this session, we’ll explore how Prophets and key figures (Maududi, Qutb, etc) responded to the unique trials of their times and took bold initiative to uplift their communities. By understanding their struggles and strategies, we’ll draw lessons on how we, too, can rise to the challenges of our time and become agents of positive change.', 'Grand Ballroom ABC', false, NULL::integer, NULL),
    (TIMESTAMPTZ '2026-07-11 12:15:00 America/New_York', TIMESTAMPTZ '2026-07-11 13:15:00 America/New_York', 'NNC (0-2 years) · The Ideal NeighborNet', 'Youth groups typically put most of their effort into marketing events, but YM strives to minimize conventional advertising by focusing on personal connection and building meaningful relationships. We will spend some time exploring different outreach strategies, with the ultimate goal of retaining members for weekly attendance, fostering brotherhood, and establishing NeighborNet in a way that can last for at least 20-30 years.(Feedback: mention outreach to different demographics)', 'Ballroom A', false, NULL::integer, NULL),
    (TIMESTAMPTZ '2026-07-11 12:15:00 America/New_York', TIMESTAMPTZ '2026-07-11 13:15:00 America/New_York', 'SR (2+ years) · The Over-Ritualization of Islam and Its Pitfalls', 'Islam is not merely a set of rituals—it is a comprehensive system meant to establish God’s sovereignty over all aspects of life. Yet over time, Tawheed has been reduced to a concept, and Islam pacified into cultural tradition. While outward forms like dress or du’as are followed, the deeper mission is neglected. This session explores how ritualism has diluted Islam’s spirit and sidelined its guidance on politics, economics, and governance.', 'Ballroom B&C', false, NULL::integer, NULL),
    (TIMESTAMPTZ '2026-07-11 13:15:00 America/New_York', TIMESTAMPTZ '2026-07-11 15:00:00 America/New_York', 'Dhuhr / Asr + Lunch', NULL, 'Lobby', true, NULL::integer, NULL),
    (TIMESTAMPTZ '2026-07-11 15:00:00 America/New_York', TIMESTAMPTZ '2026-07-11 16:00:00 America/New_York', 'NNC (0-2 years) · NN As The Vehicle For Advocacy', 'The Muslim community at large has had a difficult time increasing the number of people consistently engaged in advocacy, while also improving the quality of our work. Often, YM is seen pushing many different efforts in this space, but it is not always clear how NNs are supposed to help solve this problem. This session covers how NNs can create and grow a strong friend group that builds personal relationships, which can then be mobilized for broader causes and Islamic work such as advocacy.', 'Dulles', false, NULL::integer, 'siisntnyc'),
    (TIMESTAMPTZ '2026-07-11 15:00:00 America/New_York', TIMESTAMPTZ '2026-07-11 16:00:00 America/New_York', 'NNC (0-2 years) · Developing Yourself and Your NeighborNet Beyond NeighborNet', 'The end goal of YM is to develop brotherhood as a means of strengthening one’s deen, whether by creating Islamic workers or, at minimum, helping individuals improve their tazkiyah and personal practice of Islam. However, the mechanisms for achieving this are not always clear, especially when NN every week can feel like it is just about having fun. In this session, we will go in depth on how to establish book clubs, implement meaningful programming, and understand how to positively impact our communities.', 'LaGuardia', false, NULL::integer, NULL),
    (TIMESTAMPTZ '2026-07-11 15:00:00 America/New_York', TIMESTAMPTZ '2026-07-11 16:00:00 America/New_York', 'SR (2+ years) · Striking a Balance to Avoid Burnout', 'As leaders, it can become very difficult to push ourselves toward improvement while also encouraging others to commit to their own betterment. It is a journey with a very low success rate and one that often brings disappointments and challenges. In this session, we will discuss how to view these moments, how to get through them with a positive attitude and optimism, and how to address the dilemma of “burnout,” especially recognizing that burnout often means you are pushing yourself and that serving on an NNC or SR team is not an easy responsibility.', 'Ballroom A', false, NULL::integer, NULL),
    (TIMESTAMPTZ '2026-07-11 15:00:00 America/New_York', TIMESTAMPTZ '2026-07-11 16:00:00 America/New_York', 'SR (2+ years) · The Role of YM in the Palestinian Movement', 'YM is not a political organization, but much of our work still involves engaging with public issues and broader society. In the United States, one of the most urgent issues is support for Palestine, so this session explores how someone, beyond just their role in YM, can engage in meaningful work for Palestine in the U.S., with the long-term goal of helping end all U.S. support for Israel.', 'Ballroom B', false, NULL::integer, 'isnotreal'),
    (TIMESTAMPTZ '2026-07-11 15:00:00 America/New_York', TIMESTAMPTZ '2026-07-11 16:00:00 America/New_York', 'NNC (0-2 years), SR (2+ years) · Addressing Doubts and Muslim Youth Issues', 'This session explores common doubts, questions, and social pressures Muslim youth face while growing up in today’s environment. It will provide a grounded Islamic framework for addressing confusion around faith and identity so participants leave better equipped to support NNs through honest questions without losing connection to Allah.', 'Ballroom C', false, NULL::integer, NULL),
    (TIMESTAMPTZ '2026-07-11 16:00:00 America/New_York', TIMESTAMPTZ '2026-07-11 17:00:00 America/New_York', 'NNC (0-2 years) · Entitlement and the Discipline of Humility', 'As people who are entrusted with responsibilties and given titles that come with favors/benefits, what is the mindset we should constatnly struggle to carry and remember? How should our mindset reflect in our actions and in the way we carry ourselves and interact with others who we may be responsible for or to those we answer to? What were the lives of the Prophet SAW, sahaba, and great leaders/scholars of the past after having fame and titles and what did their zuhd look like and how can we emulate that? What are common thoughts or ideas or phrases/expectations that should be redflags as they come up in ourselves regarding stature/leadership.', 'LaGuardia', false, NULL::integer, NULL),
    (TIMESTAMPTZ '2026-07-11 16:00:00 America/New_York', TIMESTAMPTZ '2026-07-11 17:00:00 America/New_York', 'NNC (0-2 years) · Overcoming Sectarianism for a Unified Islamic Movement', 'Many of our youth often become sidetracked by online and social media debates, which heavily influence them toward specific groups, such as Deobandi, Salafi, or Sufi, consequently fueling sectarianism among Muslims. This session will explore the historical and contemporary factors contributing to divisions among Muslims while emphasizing the critical need for unity and collective action on issues such as the genocide in Gaza, the moral and social decay in the USA, and the economic injustices occurring in our local communities.', 'Reagan', false, NULL::integer, NULL),
    (TIMESTAMPTZ '2026-07-11 16:00:00 America/New_York', TIMESTAMPTZ '2026-07-11 17:00:00 America/New_York', 'SR (2+ years) · Creating a Strategy for the SR / Region', 'SR is an important concept and structure in YM. it''s the strucutre of the organization that pushes different initiatives on a local level beyond NN. What is the goal of the SR? How can we create a vision for the SR? and how can we create a strategy and long term planning to achieve the goals of YM on an SR level? This session will provide some practical examples and help with answering these questions.', 'Ballroom A', false, NULL::integer, NULL),
    (TIMESTAMPTZ '2026-07-11 16:00:00 America/New_York', TIMESTAMPTZ '2026-07-11 17:00:00 America/New_York', 'SR (2+ years) · Coalition Building to Bring about Social Change', 'Establishing justice in society requires coalition-building, which means Muslims must work alongside non-Muslims wherever there is genuine shared commitment to the common good. We cannot rely on Qur’an and Sunnah alone to persuade wider publics (because they dont believe in it lol) to address social ills; we must also demonstrate the tangible value of the solutions Islam offers in ways that serve everyone, even without explicitly naming Islam.', 'Ballroom B', false, NULL::integer, NULL),
    (TIMESTAMPTZ '2026-07-11 16:00:00 America/New_York', TIMESTAMPTZ '2026-07-11 17:00:00 America/New_York', 'SR (2+ years) · Developing a Qur''anic Worldview', 'This session explores how the Qur’an shapes the believer’s understanding of Allah, the human being, society, history, and the mission of the Ummah. It will build the foundational lens needed for Islamic work by seeing reality through revelation, measuring success by divine guidance, and aligning our priorities with the responsibility of carrying guidance to humanity.', 'Dulles', false, NULL::integer, NULL),
    (TIMESTAMPTZ '2026-07-11 17:00:00 America/New_York', TIMESTAMPTZ '2026-07-11 18:00:00 America/New_York', 'Break', NULL, 'Grand Ballroom ABC', true, NULL::integer, NULL),
    (TIMESTAMPTZ '2026-07-11 18:00:00 America/New_York', TIMESTAMPTZ '2026-07-11 19:00:00 America/New_York', 'NNC (0-2 years) · Holding Accountability in CT to Ensure Succession and Sustainability', 'Accountability is a term we often understand as chewing someone out, scolding people, or pressuring them to fulfill their assigned responsibilities and roles. However, accountability can be practiced in a way that achieves those goals without making a person feel negatively judged or hounded. The problem is that most of the accountability we see is only enough to keep someone around for their role, rather than helping them grow into responsibility. This raises the question: how can we create a culture of accountability within the NN, and eventually within an SR, that builds sustainable teams, sets a strong culture with a clear vision, and ensures the next generation of leaders does the same?', 'Ballroom A', false, NULL::integer, NULL),
    (TIMESTAMPTZ '2026-07-11 18:00:00 America/New_York', TIMESTAMPTZ '2026-07-11 19:00:00 America/New_York', 'NNC (0-2 years) · Seeking Mentorship & Conducting Shura', 'As NNC we face thousasnds of challenges that require decisions to be made. Many times we either assume that we can make the decision our own or it does not occur to us that there are experienced people around us willing to help us through these tough roadmaps. In this session, we will out line the process of how to go about making a decision that is based in the understaninds/teaching of the Prophet SAW and the sahaba. We will describe the process of making a plan and enacting that plan so that our decision have barakah and we follow the process of Shura. (IE: how to not just wing decision to problems that come about, Seeking alums, shura, SRC, CT, imams opinions)', 'Ballroom B', false, NULL::integer, NULL),
    (TIMESTAMPTZ '2026-07-11 18:00:00 America/New_York', TIMESTAMPTZ '2026-07-11 19:00:00 America/New_York', 'SR (2+ years) · Prophetic Chivalry and Preparing for Marriage', 'This session explores Prophetic chivalry as a balanced model of masculinity rooted in strength, responsibility, humility, and compassion. It will examine how brothers can prepare for marriage with a clear understanding of its purpose, the values they seek in a spouse, and the kind of family they hope to build. Rather than viewing marriage as separate from Islamic work, this session frames it as one of the most important ways an Islamic worker contributes to society and carries the mission forward.', 'LaGuardia', false, NULL::integer, 'gwagon'),
    (TIMESTAMPTZ '2026-07-11 18:00:00 America/New_York', TIMESTAMPTZ '2026-07-11 19:00:00 America/New_York', 'SR (2+ years) · YM in the Hood', 'Outreach in inner cities.', 'Ballroom C', false, NULL::integer, NULL),
    (TIMESTAMPTZ '2026-07-11 18:00:00 America/New_York', TIMESTAMPTZ '2026-07-11 19:00:00 America/New_York', 'SR (2+ years) · Responding to Rising Islamophobia and Social Crisis in the USA', 'In recent months, the United States has seen a troubling rise in Islamophobia and broader social polarization that harms both Muslim and non-Muslim communities. While awareness and responsible social media engagement are part of the solution, meaningful progress also requires sustained civic engagement. This session will outline practical steps YM can take to strengthen community resilience, build constructive relationships, and advance tangible outcomes through local civic action.', 'Dulles', false, NULL::integer, NULL),
    (TIMESTAMPTZ '2026-07-11 19:00:00 America/New_York', TIMESTAMPTZ '2026-07-11 20:00:00 America/New_York', 'Main Session · When Humanity Forgets Its Lord', 'Tawhid al-Hakimiyyah means that the oneness of Allah must be realized not only in worship, but also in collective life. Modern political systems become problematic when they grant human beings the unrestricted right to determine ultimate values and laws apart from divine guidance. Thus, the central struggle of a Muslim is to liberate humanity from servitude to man-made domination and restore servitude to Allah alone.', 'Grand Ballroom ABC', false, NULL::integer, NULL),
    (TIMESTAMPTZ '2026-07-11 20:00:00 America/New_York', TIMESTAMPTZ '2026-07-11 21:00:00 America/New_York', 'Maghrib and Isha', NULL, 'Grand Ballroom ABC', true, NULL::integer, NULL),
    (TIMESTAMPTZ '2026-07-11 21:00:00 America/New_York', TIMESTAMPTZ '2026-07-12 00:00:00 America/New_York', 'Dinner and Activities', NULL, 'Grand Ballroom ABC', true, NULL::integer, NULL),
    (TIMESTAMPTZ '2026-07-12 08:00:00 America/New_York', TIMESTAMPTZ '2026-07-12 09:00:00 America/New_York', 'Breakfast', NULL, 'Lobby', true, NULL::integer, NULL),
    (TIMESTAMPTZ '2026-07-12 09:30:00 America/New_York', TIMESTAMPTZ '2026-07-12 10:00:00 America/New_York', 'Main Session · Quran Recitation', NULL, 'Grand Ballroom ABC', false, NULL::integer, NULL),
    (TIMESTAMPTZ '2026-07-12 10:00:00 America/New_York', TIMESTAMPTZ '2026-07-12 12:30:00 America/New_York', 'NNC (0-2 years) · NNC Workshop', NULL, 'Grand Ballroom ABC', false, NULL::integer, NULL),
    (TIMESTAMPTZ '2026-07-12 10:00:00 America/New_York', TIMESTAMPTZ '2026-07-12 11:15:00 America/New_York', 'SR (2+ years) · Modern-Age of Da''wah', 'Da’wah is more than simply calling people to belief; it involves presenting Islam’s guidance through values that speak to the shared concerns of humanity. It will focus on how Muslims can bring Qur’anic principles such as justice, family, and moral clarity into public conversations in a way that is accessible, relevant, and rooted in Islamic purpose.', 'LaGuardia', false, NULL::integer, NULL),
    (TIMESTAMPTZ '2026-07-12 10:00:00 America/New_York', TIMESTAMPTZ '2026-07-12 11:15:00 America/New_York', 'SR (2+ years) · Cloud Session #1 - The Integrated Muslim: How to Stop Living Fragmented', 'This session explores how many Muslims live fragmented lives, separating deen, career, family, community work, and personal growth into disconnected boxes. Through Islamic principles and practical reflection, participants will learn how to build a more integrated life where ambition, worship, relationships, and service all move toward the same purpose. The goal is to help attendees stop merely “balancing” Islam with life and start allowing Islam to organize the whole of life.', 'Dulles', false, NULL::integer, NULL),
    (TIMESTAMPTZ '2026-07-12 10:00:00 America/New_York', TIMESTAMPTZ '2026-07-12 11:15:00 America/New_York', 'SR (2+ years) · How to Create More NN''s', 'The goal of YM is to create Islamic workers, and to increase our impact, we need to create more NNs so YM can affect more Muslim youth and more communities. However, the process for doing this is often fragmented. This session will walk through the process of starting an NN from scratch and developing it until it reaches a level where it can operate independently. NN can be a life-long thing.', 'Reagan', false, NULL::integer, NULL),
    (TIMESTAMPTZ '2026-07-12 11:15:00 America/New_York', TIMESTAMPTZ '2026-07-12 12:30:00 America/New_York', 'SR (2+ years) · Building Muslim Institutions in a Startup World', 'In a world shaped by startups, platforms, and rapid innovation, Muslim communities need leaders who can build institutions with both spiritual depth and operational excellence. This session with Ashequl Haque explores how startup principles like clear mission, strong teams, fast learning, and sustainable systems can help Muslim organizations move beyond one-off events and personality-driven work. Participants will leave with a practical vision for building projects, communities, and institutions that are rooted in sincerity, designed for impact, and strong enough to outlast any one person.', 'LaGuardia', false, NULL::integer, NULL),
    (TIMESTAMPTZ '2026-07-12 11:15:00 America/New_York', TIMESTAMPTZ '2026-07-12 12:30:00 America/New_York', 'SR (2+ years) · Cloud Coordinators', NULL, 'Dulles', false, NULL::integer, NULL),
    (TIMESTAMPTZ '2026-07-12 11:15:00 America/New_York', TIMESTAMPTZ '2026-07-12 12:30:00 America/New_York', 'SR (2+ years) · Cloud Session #2 - TBD', NULL, 'Reagan', false, NULL::integer, NULL),
    (TIMESTAMPTZ '2026-07-12 12:30:00 America/New_York', TIMESTAMPTZ '2026-07-12 13:00:00 America/New_York', 'Main Session · Closing Remarks', NULL, 'Grand Ballroom ABC', false, NULL::integer, NULL),
    (TIMESTAMPTZ '2026-07-12 13:00:00 America/New_York', TIMESTAMPTZ '2026-07-12 14:00:00 America/New_York', 'Dhuhr / Asr + Lunch', NULL, 'Grand Ballroom ABC', true, NULL::integer, NULL)
) AS v(start_at, end_at, title, description, room, is_break, capacity, code);

-- Attendees: resolve each roster email to a users row. Emails with no matching
-- user (e.g. not yet synced) are simply not inserted — no error, no orphan.
INSERT INTO conference_attendees (conference_id, user_id)
SELECT c.id, u.id
FROM conferences c
JOIN (VALUES
    ('jamil.aboushaar@youngmuslims.com'),
    ('kareem.hachmi@youngmuslims.com'),
    ('umer.shamsi@youngmuslims.com'),
    ('rayn.ali@youngmuslims.com'),
    ('ahmad.affan@youngmuslims.com'),
    ('justin.catagua@youngmuslims.com'),
    ('omair.qureshi@youngmuslims.com'),
    ('tauseef.siddique@youngmuslims.com'),
    ('syed.huzaifa@youngmuslims.com'),
    ('omar.anees@youngmuslims.com'),
    ('malik.musleh@youngmuslims.com'),
    ('murad.sawalha@youngmuslims.com'),
    ('aqeel.naina@youngmuslims.com'),
    ('ibraheem.mir@youngmuslims.com'),
    ('salman.siddik@youngmuslims.com'),
    ('haroon.arain@youngmuslims.com'),
    ('zayd.elhedoudy@youngmuslims.com'),
    ('abdul-malik.aziz@youngmuslims.com'),
    ('muhammad.hameed@youngmuslims.com'),
    ('naseerullah.fazili@youngmuslims.com'),
    ('talaal.ahmad@youngmuslims.com'),
    ('ibraheem.mahmood@youngmuslims.com'),
    ('mahmoud.desouky@youngmuslims.com'),
    ('ahmed.minih@youngmuslims.com'),
    ('omar.ababneh@youngmuslims.com'),
    ('yousuf.laeeq@youngmuslims.com'),
    ('mahmoud.mohamed@youngmuslims.com'),
    ('moiz.shah@youngmuslims.com'),
    ('rami.sawalha@youngmuslims.com'),
    ('muneeb.butt@youngmuslims.com'),
    ('wisam.selim@youngmuslims.com'),
    ('muhammad.hasnie@youngmuslims.com'),
    ('muadh.ali@youngmuslims.com'),
    ('brahim.nid-youssef@youngmuslims.com'),
    ('saifeldeen.sebaei@youngmuslims.com'),
    ('muhammad.mazhar@youngmuslims.com'),
    ('ehab.faraj@youngmuslims.com'),
    ('sg@youngmuslims.com'),
    ('mohtadi.mahim@youngmuslims.com'),
    ('mustafa.ehsan@youngmuslims.com'),
    ('hassan.jafri@youngmuslims.com'),
    ('noah.k.jaber@youngmuslims.com'),
    ('ammar.hussain@youngmuslims.com'),
    ('ahmmad.halak@youngmuslims.com'),
    ('zaid.khan@youngmuslims.com'),
    ('aftab.khan@youngmuslims.com'),
    ('maaz.motiwala@youngmuslims.com'),
    ('obaid.bari@youngmuslims.com'),
    ('maaz.chaudhry@youngmuslims.com'),
    ('aliaan.patel@youngmuslims.com'),
    ('furqan.rehman@youngmuslims.com'),
    ('munir.abdullah@youngmuslims.com'),
    ('yusuf.jummani@youngmuslims.com'),
    ('tawfic.elghor@youngmuslims.com'),
    ('uk@youngmuslims.com'),
    ('youssef.ege@youngmuslims.com'),
    ('luqman.abdali@youngmuslims.com'),
    ('ahmad.zoghol@youngmuslims.com'),
    ('mohammad.sohaib@youngmuslims.com'),
    ('aadil.malik@youngmuslims.com'),
    ('abdulrahman.mohammed@youngmuslims.com'),
    ('firas.iqbal@youngmuslims.com'),
    ('nabeel.enver@youngmuslims.com'),
    ('hassan.sana@youngmuslims.com'),
    ('umar.siddiqui@youngmuslims.com'),
    ('baari.mohammed@youngmuslims.com'),
    ('raghib.hossain@youngmuslims.com'),
    ('amaan.ghoghawala@youngmuslims.com'),
    ('mujtaba.ather@youngmuslims.com'),
    ('bilal.haq@youngmuslims.com'),
    ('saad.jaffery@youngmuslims.com'),
    ('muzammil.javed@youngmuslims.com'),
    ('areeb.siddiqui@youngmuslims.com'),
    ('zabhi.syed@youngmuslims.com'),
    ('rafay.malik@youngmuslims.com'),
    ('aqib.waheed@youngmuslims.com'),
    ('maaz.suglatwala@youngmuslims.com'),
    ('abdullah.mujahid@youngmuslims.com'),
    ('maaz.naqvi@youngmuslims.com'),
    ('naurez.seyed@youngmuslims.com'),
    ('mahdi.hussain@youngmuslims.com'),
    ('taha.master@youngmuslims.com'),
    ('akkad.alzayady@youngmuslims.com'),
    ('kareem.bacchus@youngmuslims.com'),
    ('amir.asror@youngmuslims.com'),
    ('adam.lahoumah@youngmuslims.com'),
    ('ahmad.arab@youngmuslims.com'),
    ('muhib.sheikh@youngmuslims.com'),
    ('abdallah.sakallah@youngmuslims.com'),
    ('hadi.rana@youngmuslims.com'),
    ('azzaam.baig@youngmuslims.com'),
    ('fowwaz.moeen@youngmuslims.com'),
    ('ammar.salama@youngmuslims.com'),
    ('yussuf.nasri@youngmuslims.com'),
    ('shaheer.siddiqui@youngmuslims.com'),
    ('ahmad.somakia@youngmuslims.com'),
    ('ahmed.elsaadani@youngmuslims.com'),
    ('huzaifa.siddiqi@youngmuslims.com'),
    ('abdullah.mohammed@youngmuslims.com'),
    ('nabeel.mohammad@youngmuslims.com'),
    ('islam.alzhogi@youngmuslims.com'),
    ('mahmoud.elsabbal@youngmuslims.com'),
    ('nazir.alnahas@youngmuslims.com'),
    ('ammar.siddiqui@youngmuslims.com'),
    ('anas.dahrouj@youngmuslims.com'),
    ('zeshan.khatri@youngmuslims.com'),
    ('taaha.dandia@youngmuslims.com'),
    ('shahzaib.vohra@youngmuslims.com'),
    ('hassan.ali@youngmuslims.com'),
    ('shaheer.ghazenfer@youngmuslims.com'),
    ('shujah.malhi@youngmuslims.com'),
    ('hamzah.ismail@youngmuslims.com'),
    ('ayaan.mazhar@youngmuslims.com'),
    ('umer.mansuri@youngmuslims.com'),
    ('valeed.siddiqui@youngmuslims.com'),
    ('abdullah.khawaja@youngmuslims.com'),
    ('ziyaad.aziz@youngmuslims.com'),
    ('tanzeel.jaffery@youngmuslims.com'),
    ('aqib.chaudary@youngmuslims.com'),
    ('omar.hai@youngmuslims.com'),
    ('zakreya.khan@youngmuslims.com'),
    ('wahez.ali@youngmuslims.com'),
    ('ali.ubaid@youngmuslims.com'),
    ('faizaan.quadri@youngmuslims.com'),
    ('faizaan.ahmed@youngmuslims.com'),
    ('reyan.alam@youngmuslims.com'),
    ('imaad.khan@youngmuslims.com'),
    ('hamza.mufti@youngmuslims.com'),
    ('kasim.ali@youngmuslims.com'),
    ('moussa.wood@youngmuslims.com'),
    ('muhammad.abdullah@youngmuslims.com'),
    ('aqil@youngmuslims.com'),
    ('saleem.shareef@youngmuslims.com'),
    ('adam.kassem@youngmuslims.com'),
    ('dominic.j.reddick@youngmuslims.com'),
    ('sameer.mahmood@youngmuslims.com'),
    ('hamza.laith.khan@youngmuslims.com'),
    ('omar.siddiqui@youngmuslims.com'),
    ('dawood.ibrahim@youngmuslims.com'),
    ('muhammad.faheem@youngmuslims.com'),
    ('rayyan.jaffer@youngmuslims.com'),
    ('farhan.ali@youngmuslims.com'),
    ('rajin.hossain@youngmuslims.com'),
    ('fahad.faisal@youngmuslims.com'),
    ('moaz.ateya@youngmuslims.com'),
    ('muneeb.syed@youngmuslims.com'),
    ('danial.khan@youngmuslims.com'),
    ('abdulmajeed.tarabishy@youngmuslims.com'),
    ('ali.rashada@youngmuslims.com'),
    ('ibrahim.shakir@youngmuslims.com'),
    ('musa.karim@youngmuslims.com'),
    ('ahmad.kharfan@youngmuslims.com'),
    ('adam.hasan@youngmuslims.com'),
    ('abdullah.rafiq@youngmuslims.com'),
    ('ali.syed@youngmuslims.com'),
    ('asad.y.shahzad@youngmuslims.com'),
    ('musa.shareef@youngmuslims.com'),
    ('hammad.mohammed@youngmuslims.com'),
    ('zain.amanullah@youngmuslims.com'),
    ('yunus.kounkourou@youngmuslims.com'),
    ('saabir.beig@youngmuslims.com'),
    ('zaid.syed@youngmuslims.com'),
    ('mohamed.eljack@youngmuslims.com'),
    ('mahir.saad@youngmuslims.com'),
    ('mahdi.talha@youngmuslims.com'),
    ('hamza.qureshi@youngmuslims.com'),
    ('omar.abdullahi@youngmuslims.com'),
    ('saad.ijaz@youngmuslims.com'),
    ('muhammed.lat@youngmuslims.com'),
    ('abdul.bashir@youngmuslims.com'),
    ('taha.zia@youngmuslims.com'),
    ('saifullah.mir@youngmuslims.com'),
    ('tamer.akhdar@youngmuslims.com'),
    ('johaer.jilani@youngmuslims.com'),
    ('khalid.abdullahi@youngmuslims.com'),
    ('rayyan.hasan@youngmuslims.com'),
    ('zakariya.lakhani@youngmuslims.com'),
    ('ibrahim.adil@youngmuslims.com'),
    ('amin.badmos@youngmuslims.com'),
    ('sami.hameed@youngmuslims.com'),
    ('ahmed.filly@youngmuslims.com'),
    ('burhanulhaq.brula@youngmuslims.com'),
    ('farhanahmed@youngmuslims.com'),
    ('yusuf.ahmad@youngmuslims.com'),
    ('moeez.shahid@youngmuslims.com'),
    ('ahmed.sharairi@youngmuslims.com'),
    ('samih.wadi@youngmuslims.com'),
    ('rizwan.a.siddiqui@youngmuslims.com'),
    ('elias.tanvir@youngmuslims.com'),
    ('ahmed.ellithy@youngmuslims.com'),
    ('rayyan.sarkhot@youngmuslims.com'),
    ('ayman.sharieff@youngmuslims.com'),
    ('muhammad.shaaf@youngmuslims.com'),
    ('abdullah.azmy@youngmuslims.com'),
    ('ibraheem.zia@youngmuslims.com'),
    ('amer.mahdi@youngmuslims.com'),
    ('ziyad.yousif@youngmuslims.com'),
    ('malik.yassin@youngmuslims.com'),
    ('hanzalah.qamar@youngmuslims.com'),
    ('abdul.ahmed@youngmuslims.com'),
    ('tousif.pervez@youngmuslims.com'),
    ('hazef.iqbal@youngmuslims.com'),
    ('basith.mohammed@youngmuslims.com'),
    ('ahmed.salem@youngmuslims.com')
) AS roster(email) ON TRUE
JOIN public.users u ON lower(u.email) = roster.email
WHERE c.name = 'YMLC 2026'
ON CONFLICT (conference_id, user_id) DO NOTHING;

COMMIT;

-- Sanity checks (run after COMMIT):
--   SELECT count(*) FROM sessions s JOIN conferences c ON c.id=s.conference_id
--     WHERE c.name='YMLC 2026';                        -- expect 42
--   SELECT count(*) FROM conference_attendees ca JOIN conferences c ON c.id=ca.conference_id
--     WHERE c.name='YMLC 2026';                        -- expect <= 204
