// Mock data for People Directory
// TODO: Replace with Supabase data fetching when schema is migrated

import type { PersonListItem, FilterCategory, PeopleFilters } from './types'

// Realistic mock people data based on YM hierarchy
export const MOCK_PEOPLE: PersonListItem[] = [
  {
    id: '1',
    firstName: 'Ahmed',
    lastName: 'Khan',
    email: 'ahmed.khan@youngmuslims.com',
    avatarUrl: undefined,
    region: { id: 'south', name: 'South' },
    subregion: { id: 'houston', name: 'Houston' },
    neighborNet: { id: 'nn-houston-west', name: 'Houston West' },
    roles: [
      { id: 'nnc', name: 'NeighborNet Coordinator', category: 'neighbor_net' },
      { id: 'cloud_member', name: 'Cloud Member', category: 'cloud' },
    ],
    skills: ['Leadership', 'Public Speaking', 'Event Planning'],
    yearsInYM: 5,
  },
  {
    id: '2',
    firstName: 'Sara',
    lastName: 'Ali',
    email: 'sara.ali@youngmuslims.com',
    avatarUrl: undefined,
    region: { id: 'south', name: 'South' },
    subregion: { id: 'houston', name: 'Houston' },
    neighborNet: { id: 'nn-houston-east', name: 'Houston East' },
    roles: [
      { id: 'src', name: 'Sub-Regional Coordinator', category: 'subregional' },
    ],
    skills: ['Mentoring', 'Project Management'],
    yearsInYM: 8,
  },
  {
    id: '3',
    firstName: 'Omar',
    lastName: 'Hassan',
    email: 'omar.hassan@youngmuslims.com',
    avatarUrl: undefined,
    region: { id: 'northeast', name: 'Northeast' },
    subregion: { id: 'nyc', name: 'New York City' },
    neighborNet: { id: 'nn-brooklyn', name: 'Brooklyn' },
    roles: [
      { id: 'rc', name: 'Regional Coordinator', category: 'council' },
    ],
    skills: ['Strategic Planning', 'Team Building', 'Fundraising'],
    yearsInYM: 12,
  },
  {
    id: '4',
    firstName: 'Fatima',
    lastName: 'Malik',
    email: 'fatima.malik@youngmuslims.com',
    avatarUrl: undefined,
    region: { id: 'midwest', name: 'Midwest' },
    subregion: { id: 'chicago', name: 'Chicago' },
    neighborNet: { id: 'nn-chicago-north', name: 'Chicago North' },
    roles: [
      { id: 'dept_head', name: 'Department Head', category: 'cabinet' },
      { id: 'cloud_coord', name: 'Cloud Coordinator', category: 'cloud' },
    ],
    skills: ['Marketing', 'Content Creation', 'Social Media'],
    yearsInYM: 6,
  },
  {
    id: '5',
    firstName: 'Yusuf',
    lastName: 'Rahman',
    email: 'yusuf.rahman@youngmuslims.com',
    avatarUrl: undefined,
    region: { id: 'west', name: 'West' },
    subregion: { id: 'la', name: 'Los Angeles' },
    neighborNet: { id: 'nn-la-central', name: 'LA Central' },
    roles: [
      { id: 'ns_member', name: 'NS Member', category: 'ns' },
      { id: 'cabinet_sg', name: 'Cabinet Secretary General', category: 'cabinet' },
    ],
    skills: ['Leadership', 'Strategic Planning', 'Public Speaking'],
    yearsInYM: 15,
  },
  {
    id: '6',
    firstName: 'Aisha',
    lastName: 'Patel',
    email: 'aisha.patel@youngmuslims.com',
    avatarUrl: undefined,
    region: { id: 'south', name: 'South' },
    subregion: { id: 'dallas', name: 'Dallas' },
    neighborNet: { id: 'nn-dallas-north', name: 'Dallas North' },
    roles: [
      { id: 'team_lead', name: 'Team Lead', category: 'cabinet' },
    ],
    skills: ['Design', 'UI/UX', 'Branding'],
    yearsInYM: 4,
  },
  {
    id: '7',
    firstName: 'Ibrahim',
    lastName: 'Johnson',
    email: 'ibrahim.johnson@youngmuslims.com',
    avatarUrl: undefined,
    region: { id: 'northeast', name: 'Northeast' },
    subregion: { id: 'boston', name: 'Boston' },
    neighborNet: { id: 'nn-boston-cambridge', name: 'Cambridge' },
    roles: [
      { id: 'ct_member', name: 'Core Team Member', category: 'neighbor_net' },
    ],
    skills: ['Teaching', 'Curriculum Development'],
    yearsInYM: 3,
  },
  {
    id: '8',
    firstName: 'Mariam',
    lastName: 'Ahmed',
    email: 'mariam.ahmed@youngmuslims.com',
    avatarUrl: undefined,
    region: { id: 'midwest', name: 'Midwest' },
    subregion: { id: 'detroit', name: 'Detroit' },
    neighborNet: { id: 'nn-dearborn', name: 'Dearborn' },
    roles: [
      { id: 'nnc', name: 'NeighborNet Coordinator', category: 'neighbor_net' },
      { id: 'reg_cloud_rep', name: 'Regional Cloud Rep', category: 'regional' },
    ],
    skills: ['Community Outreach', 'Event Planning', 'Volunteer Management'],
    yearsInYM: 7,
  },
  {
    id: '9',
    firstName: 'Zaid',
    lastName: 'Williams',
    email: 'zaid.williams@youngmuslims.com',
    avatarUrl: undefined,
    region: { id: 'west', name: 'West' },
    subregion: { id: 'seattle', name: 'Seattle' },
    neighborNet: { id: 'nn-seattle-eastside', name: 'Eastside' },
    roles: [
      { id: 'sr_sg', name: 'SR Secretary General', category: 'subregional' },
    ],
    skills: ['Administration', 'Documentation', 'Process Improvement'],
    yearsInYM: 5,
  },
  {
    id: '10',
    firstName: 'Khadija',
    lastName: 'Brown',
    email: 'khadija.brown@youngmuslims.com',
    avatarUrl: undefined,
    region: { id: 'south', name: 'South' },
    subregion: { id: 'atlanta', name: 'Atlanta' },
    neighborNet: { id: 'nn-atlanta-north', name: 'Atlanta North' },
    roles: [
      { id: 'team_member', name: 'Team Member', category: 'cabinet' },
      { id: 'cloud_member', name: 'Cloud Member', category: 'cloud' },
    ],
    skills: ['Writing', 'Communications', 'Public Relations'],
    yearsInYM: 2,
  },
  {
    id: '11',
    firstName: 'Hamza',
    lastName: 'Sheikh',
    email: 'hamza.sheikh@youngmuslims.com',
    avatarUrl: undefined,
    region: { id: 'northeast', name: 'Northeast' },
    subregion: { id: 'philadelphia', name: 'Philadelphia' },
    neighborNet: { id: 'nn-philly-main', name: 'Main Line' },
    roles: [
      { id: 'src', name: 'Sub-Regional Coordinator', category: 'subregional' },
      { id: 'reg_special_proj', name: 'Regional Special Projects', category: 'regional' },
    ],
    skills: ['Project Management', 'Logistics', 'Budgeting'],
    yearsInYM: 9,
  },
  {
    id: '12',
    firstName: 'Nadia',
    lastName: 'Hussain',
    email: 'nadia.hussain@youngmuslims.com',
    avatarUrl: undefined,
    region: { id: 'midwest', name: 'Midwest' },
    subregion: { id: 'minneapolis', name: 'Minneapolis' },
    neighborNet: { id: 'nn-twin-cities', name: 'Twin Cities' },
    roles: [
      { id: 'nnc', name: 'NeighborNet Coordinator', category: 'neighbor_net' },
    ],
    skills: ['Youth Mentoring', 'Program Development', 'Facilitation'],
    yearsInYM: 4,
  },
]

// Filter options for the dropdown menus
// TODO: Fetch these from Supabase tables when schema is migrated
export const FILTER_CATEGORIES: FilterCategory[] = [
  {
    id: 'regions',
    label: 'Regions',
    options: [
      { id: 'south', name: 'South' },
      { id: 'northeast', name: 'Northeast' },
      { id: 'midwest', name: 'Midwest' },
      { id: 'west', name: 'West' },
    ],
  },
  {
    id: 'subregions',
    label: 'Subregions',
    options: [
      { id: 'houston', name: 'Houston' },
      { id: 'dallas', name: 'Dallas' },
      { id: 'atlanta', name: 'Atlanta' },
      { id: 'nyc', name: 'New York City' },
      { id: 'boston', name: 'Boston' },
      { id: 'philadelphia', name: 'Philadelphia' },
      { id: 'chicago', name: 'Chicago' },
      { id: 'detroit', name: 'Detroit' },
      { id: 'minneapolis', name: 'Minneapolis' },
      { id: 'la', name: 'Los Angeles' },
      { id: 'seattle', name: 'Seattle' },
    ],
  },
  {
    id: 'neighborNets',
    label: 'NeighborNets',
    options: [
      { id: 'nn-houston-west', name: 'Houston West' },
      { id: 'nn-houston-east', name: 'Houston East' },
      { id: 'nn-dallas-north', name: 'Dallas North' },
      { id: 'nn-atlanta-north', name: 'Atlanta North' },
      { id: 'nn-brooklyn', name: 'Brooklyn' },
      { id: 'nn-boston-cambridge', name: 'Cambridge' },
      { id: 'nn-philly-main', name: 'Main Line' },
      { id: 'nn-chicago-north', name: 'Chicago North' },
      { id: 'nn-dearborn', name: 'Dearborn' },
      { id: 'nn-twin-cities', name: 'Twin Cities' },
      { id: 'nn-la-central', name: 'LA Central' },
      { id: 'nn-seattle-eastside', name: 'Eastside' },
    ],
  },
  {
    id: 'roles',
    label: 'Roles',
    options: [
      { id: 'ns_member', name: 'NS Member' },
      { id: 'rc', name: 'Regional Coordinator' },
      { id: 'src', name: 'Sub-Regional Coordinator' },
      { id: 'sr_sg', name: 'SR Secretary General' },
      { id: 'nnc', name: 'NeighborNet Coordinator' },
      { id: 'ct_member', name: 'Core Team Member' },
      { id: 'cloud_coord', name: 'Cloud Coordinator' },
      { id: 'cloud_member', name: 'Cloud Member' },
      { id: 'cabinet_sg', name: 'Cabinet Secretary General' },
      { id: 'dept_head', name: 'Department Head' },
      { id: 'team_lead', name: 'Team Lead' },
      { id: 'team_member', name: 'Team Member' },
      { id: 'reg_cloud_rep', name: 'Regional Cloud Rep' },
      { id: 'reg_special_proj', name: 'Regional Special Projects' },
    ],
  },
  {
    id: 'skills',
    label: 'Skills',
    options: [
      { id: 'leadership', name: 'Leadership' },
      { id: 'public-speaking', name: 'Public Speaking' },
      { id: 'event-planning', name: 'Event Planning' },
      { id: 'mentoring', name: 'Mentoring' },
      { id: 'project-management', name: 'Project Management' },
      { id: 'strategic-planning', name: 'Strategic Planning' },
      { id: 'team-building', name: 'Team Building' },
      { id: 'fundraising', name: 'Fundraising' },
      { id: 'marketing', name: 'Marketing' },
      { id: 'content-creation', name: 'Content Creation' },
      { id: 'social-media', name: 'Social Media' },
      { id: 'design', name: 'Design' },
      { id: 'teaching', name: 'Teaching' },
      { id: 'community-outreach', name: 'Community Outreach' },
      { id: 'writing', name: 'Writing' },
    ],
  },
  {
    id: 'projectTypes',
    label: 'Project Types',
    options: [
      { id: 'convention', name: 'Convention' },
      { id: 'retreat', name: 'Retreat' },
      { id: 'youth-camp', name: 'Youth Camp' },
      { id: 'conference', name: 'Conference' },
      { id: 'workshop', name: 'Workshop' },
      { id: 'fundraiser', name: 'Fundraiser' },
    ],
  },
  {
    id: 'projectRoles',
    label: 'Project Roles',
    options: [
      { id: 'project-lead', name: 'Project Lead' },
      { id: 'volunteer-coord', name: 'Volunteer Coordinator' },
      { id: 'logistics', name: 'Logistics' },
      { id: 'marketing', name: 'Marketing' },
      { id: 'finance', name: 'Finance' },
      { id: 'volunteer', name: 'Volunteer' },
    ],
  },
]

// Helper to get initial empty filters
export function getInitialFilters(): PeopleFilters {
  return {
    search: '',
    regions: [],
    subregions: [],
    neighborNets: [],
    roles: [],
    projectTypes: [],
    projectRoles: [],
    skills: [],
    yearsInYM: undefined,
  }
}
