#!/usr/bin/env bun
/**
 * Bundle size guardrail.
 *
 * Reads `.next/app-build-manifest.json`, sums the GZIPPED size of every chunk
 * referenced by each route, and compares against `bundle-size-baseline.json`.
 *
 * Why gzipped sizes: chunk files vary in raw byte length across bundler/runtime
 * minor versions even when the underlying source is identical, which makes raw
 * on-disk sizes flaky in CI vs. local. gzip(content) is byte-identical for
 * byte-identical content (zlib level 9 is deterministic), so cross-environment
 * variance shrinks dramatically when we hash that representation instead.
 *
 * Modes:
 *   default       → compare against baseline; write baseline if missing.
 *   --update      → overwrite the baseline with current sizes (after intentional changes).
 *   --check-only  → compare against baseline; FAIL if baseline is missing.
 *                   Use this in PR CI so PRs can never silently bootstrap a baseline.
 *
 * The companion workflow `.github/workflows/bundle-baseline.yml` runs `--update`
 * on push to main and commits the regenerated baseline back, which keeps the
 * checked-in file aligned with the CI build environment.
 */

import { readFileSync, writeFileSync, existsSync } from 'node:fs'
import { gzipSync } from 'node:zlib'
import { join } from 'node:path'

const REGRESSION_THRESHOLD = 0.1 // 10% allowed growth before failing
const ROOT = process.cwd()
const NEXT_DIR = join(ROOT, '.next')
const MANIFEST = join(NEXT_DIR, 'app-build-manifest.json')
const BASELINE_PATH = join(ROOT, 'bundle-size-baseline.json')

interface Manifest {
  pages: Record<string, string[]>
}

interface Baseline {
  generatedAt: string
  metric: 'gzip'
  totalsByRoute: Record<string, number>
}

function loadManifest(): Manifest {
  if (!existsSync(MANIFEST)) {
    console.error(`No manifest at ${MANIFEST}. Run \`bun run build\` first.`)
    process.exit(1)
  }
  return JSON.parse(readFileSync(MANIFEST, 'utf-8')) as Manifest
}

function gzippedSize(filePath: string): number {
  const content = readFileSync(filePath)
  return gzipSync(content, { level: 9 }).length
}

function computeRouteSizes(manifest: Manifest): Record<string, number> {
  const result: Record<string, number> = {}
  for (const [route, chunks] of Object.entries(manifest.pages)) {
    let total = 0
    for (const chunk of chunks) {
      const p = join(NEXT_DIR, chunk)
      if (existsSync(p)) total += gzippedSize(p)
    }
    result[route] = total
  }
  return result
}

function formatBytes(bytes: number): string {
  if (bytes < 1024) return `${bytes} B`
  if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(1)} kB`
  return `${(bytes / 1024 / 1024).toFixed(2)} MB`
}

function ghWarning(line: string): string {
  // Surface as a GitHub Actions PR annotation when running in CI.
  return process.env.GITHUB_ACTIONS ? `::warning::${line.trim()}` : line
}

function main() {
  const update = process.argv.includes('--update')
  const checkOnly = process.argv.includes('--check-only')
  const manifest = loadManifest()
  const current = computeRouteSizes(manifest)

  if (update) {
    const baseline: Baseline = {
      generatedAt: new Date().toISOString(),
      metric: 'gzip',
      totalsByRoute: current,
    }
    writeFileSync(BASELINE_PATH, JSON.stringify(baseline, null, 2) + '\n')
    console.log(
      `Wrote gzip baseline for ${Object.keys(current).length} routes to ${BASELINE_PATH}`,
    )
    return
  }

  if (!existsSync(BASELINE_PATH)) {
    if (checkOnly) {
      console.error(
        'No bundle-size-baseline.json found. The baseline is generated by the ' +
          '`Update bundle size baseline` workflow on push to main. ' +
          'If this is the first run, merge once to seed it.',
      )
      process.exit(1)
    }
    const baseline: Baseline = {
      generatedAt: new Date().toISOString(),
      metric: 'gzip',
      totalsByRoute: current,
    }
    writeFileSync(BASELINE_PATH, JSON.stringify(baseline, null, 2) + '\n')
    console.log(
      `Wrote initial gzip baseline for ${Object.keys(current).length} routes to ${BASELINE_PATH}`,
    )
    return
  }

  const baseline = JSON.parse(readFileSync(BASELINE_PATH, 'utf-8')) as Baseline
  if (baseline.metric !== 'gzip') {
    console.error(
      `Baseline metric is "${baseline.metric ?? 'raw'}" but this script measures gzip. ` +
        'Re-run with --update (locally or via the bundle-baseline workflow on main) to refresh.',
    )
    process.exit(1)
  }

  const regressions: string[] = []
  const routeChanges: string[] = []
  const warnings: string[] = []

  for (const [route, size] of Object.entries(current)) {
    const baseSize = baseline.totalsByRoute[route]
    if (baseSize === undefined) {
      routeChanges.push(`  + ${route}: ${formatBytes(size)} (new route)`)
      continue
    }
    const delta = size - baseSize
    const pct = baseSize === 0 ? 0 : delta / baseSize
    if (pct > REGRESSION_THRESHOLD) {
      regressions.push(
        `  ✗ ${route}: ${formatBytes(baseSize)} → ${formatBytes(size)} (+${(pct * 100).toFixed(1)}%)`,
      )
    } else if (pct > REGRESSION_THRESHOLD / 2) {
      warnings.push(
        `  ! ${route}: ${formatBytes(baseSize)} → ${formatBytes(size)} (+${(pct * 100).toFixed(1)}%)`,
      )
    }
  }

  for (const route of Object.keys(baseline.totalsByRoute)) {
    if (!(route in current)) {
      routeChanges.push(`  - ${route}: removed`)
    }
  }

  if (routeChanges.length > 0) {
    console.log('Route changes:')
    for (const line of routeChanges) console.log(line)
  }
  if (warnings.length > 0) {
    console.log(`\nApproaching ${REGRESSION_THRESHOLD * 100}% gzip growth:`)
    for (const line of warnings) console.log(ghWarning(`Bundle size: ${line.trim()}`))
  }
  if (regressions.length > 0) {
    console.error(`\nBundle size regression (>${REGRESSION_THRESHOLD * 100}% gzip over baseline):`)
    for (const line of regressions) console.error(line)
    console.error(
      '\nIf this growth is intentional, regenerate the baseline by merging to main ' +
        '(workflow `bundle-baseline` will commit a refresh) or locally via ' +
        '`bun run bundle:baseline` and commit the result.',
    )
    process.exit(1)
  }

  console.log(
    `\nBundle size OK (${Object.keys(current).length} routes, gzip threshold ${REGRESSION_THRESHOLD * 100}%).`,
  )
}

main()
